---
- name: Setup Virtualenv
  pip: executable=pip3 virtualenv={{ virtualenv_path }} virtualenv_command=virtualenv-3.4 requirements={{ project_root_path }}/requirements.txt

- name: Install some dev tools
  sudo: yes
  pip: name={{ item }} executable=pip3 virtualenv={{ virtualenv_path }}
  with_items:
    - ipdb
    - ipython
    - django-extensions

- name: Django db
  django_manage: command={{ item }} app_path={{ project_root_path }} virtualenv={{ virtualenv_path }}
  with_items:
    - syncdb
    - migrate

- name: Populate database
  django_manage: command={{ item }} app_path={{ project_root_path }} virtualenv={{ virtualenv_path }}
  with_items:
    - setup_fb
    - load_users
    - create_timetable
    - create_events
    - create_classes
    - create_bookings
    - create_blocktypes

